### ISSUE TITLE
add nginx proxy setup

### ISSUE THREAD

**Issue by vkhatri** [criteo-cookbooks/rundeck-server#20]
hello! wanted to check first before i submit a PR to setup `nginx` vhost setup for rundeck. 

do we consider `nginx` setup under the scope of this cookbook or it is up to the user to manage via a wrapper cookbook?

**Comment by jmauro** [comment]
Hey Virender,

I think the idea of this cookbook is really just to setup rundeck, so
setting up a nginx wrapper cookbook on top of rundeck makes sense.
We don't want to mix too much component into a single cookbook.

Regards,
JM

**Comment by vkhatri** [comment]
@jmauro thank you for the quick response.
