### ISSUE TITLE
add rubocop lint

### ISSUE THREAD

**Issue by vkhatri** [criteo-cookbooks/rundeck-server#24]
i noticed that `rubocop` lint is not added, i will submit a PR if sound good.

**Comment by jmauro** [comment]
Hey Virender,

At criteo, we don't enforce the usage of rubocop even if a lot of us use it
anyway. But if you wanna do it why not, this could lead to an internal
discussion.

Regards,
Jeremy Mauro
Le 12 oct. 2015 22:28, "Virender Khatri" <notifications@github.com> a
écrit :

**Comment by vkhatri** [comment]
@jmauro thanks! appreciate your consideration. i will wait for your decision.

**Comment by kamaradclimber** [comment]
Sorry for very slow answer on this issue. We've end up adding rubocop linting in the travis CI.
So I think we can close this ticket.

Thanks !
