### ISSUE TITLE
Error pycurl 14, could not find repomd.xml?

### ISSUE THREAD

**Issue by ilovemysillybanana** [criteo-cookbooks/rundeck-server#38]
I keep getting that when I try to converge this cookbook, anyone know why that might be?
I'm doing a clean clone of this repo and trying to converge and it fails each time.

**Comment by jmauro** [comment]
Hey,

Seems to be a repo yum issue, apparently yum does not seem to get the yum meta data. We have to dig more and see if rundeck has changed its yum repository.

**Comment by ilovemysillybanana** [comment]
In the meanwhile, do you know of a work around where I could specify where to find that file or to just skip entirely?

**Comment by jmauro** [comment]
Hey, 

We are using the following URL: http://dl.bintray.com/rundeck/rundeck-rpm/ does it still work?
