### ISSUE TITLE
Rundeck Server 2.7.x+

### ISSUE THREAD

**Issue by isuftin** [criteo-cookbooks/rundeck-server#43]
This cookbook does not seem to work for Rundeck Server versions >2.7.x

The cookbook run completes as expected but when I try to start the service, the service immediately crashes.

I assume one of the issues is that as per the [release notes](http://rundeck.org/docs/upgrading/index.html#debianrpm-startup-script-changes), `/etc/rundeck/profile` is no longer used.

Also, the `run` CLI tool as well as others [have been removed](http://rundeck.org/docs/upgrading/index.html#cli-tools-are-gone)

Is this a known issue that is being worked on?

**Comment by kamaradclimber** [comment]
Hello @isuftin,
thanks for the report, this issue is not being worked on at the moment, we use 2.6.4-1 internally.
We would be really glad to review a PR if you submitted one.

**Comment by kamaradclimber** [comment]
fixed by #44
