### ISSUE TITLE
Create 1.3.1 tag

### ISSUE THREAD

**Issue by isuftin** [criteo-cookbooks/rundeck-server#49]
Tag https://github.com/criteo-cookbooks/rundeck-server/commit/6d6e3964135a3fb9c5e6f30785ac4e7f2751b94e as 1.3.1

Users using 1.3.0 with default settings will end up downloading a broken Rundeck CLI from Rundeck as 1.3.0 points to 1.0.4 Rundeck CLI which does not have the ability to use a config file for configuration

**Comment by kamaradclimber** [comment]
done
