### ISSUE TITLE
Update supermarket with new version and yum constraint

### ISSUE THREAD

**Issue by fphilippon** [criteo-cookbooks/rundeck-server#60]
Hello,

Do you plan to push an updated version of the cookbook to the Chef supermarket?

Also is the constraint on the yum cookbook (< 5.0.0) still needed?
We could use the native yum_repository chef resource available since 12.14

Thanks!

**Comment by kamaradclimber** [comment]
Hello @fphilippon,

I've pushed a new version to the supermarket a few days ago.
I'll have a look regarding the yum constraint
