### ISSUE TITLE
Default recipe performs curl check against hard-coded HTTP port

### ISSUE THREAD

**Issue by isuftin** [criteo-cookbooks/rundeck-server#62]
I have Rundeck running on HTTPS only on port 8443.

The default recipe checks against a hard-coded HTTP port 4440. If there is nothing listening on this port (which is completely valid), the default recipe fails.

https://github.com/criteo-cookbooks/rundeck-server/blob/master/recipes/default.rb#L22-L26

Change this recipe to pick up whether Rundeck is running @ http or https and which port that is set to.

**Comment by isuftin** [comment]
This was introduced in 1.6.0

**Comment by kamaradclimber** [comment]
you're right, would you be kind enough to provide a patch?

**Comment by isuftin** [comment]
https://github.com/criteo-cookbooks/rundeck-server/pull/63

**Comment by kamaradclimber** [comment]
Fixed by #63 , thanks @isuftin
